### ISSUE TITLE
Deployment fails when template stored on VMFS5 and deployment done on VMFS6

### ISSUE THREAD

**Issue by f97johan** [aws/eks-anywhere#158] opened 2021-09-09 21:01 UTC
**What happened**:
When eksctl anywhere create ... created the bottlerocket template, it ended up on a VMFS5 volume by default. When the installer subsequently attempted to clone the template to VMs, it got stuck in a seemingly infinite loop of failed operations, referencing "the specified delta disk format 'redoLogFormat' is not supported". Thousands of attempts where made, and the only way to stop it (well, the way I realized at the time at least) was to convert the template to a VM and then delete it.

**What you expected to happen**:
Cloning the template to VMs should work.

**How to reproduce it (as minimally and precisely as possible)**:
1. VM Template on VMFS5
2. EKSA pointing to a VMFS6 datastore for the VMs
3. Ruh eksctl anywhaere create ...

**Anything else we need to know?**:

Converting the template to a VM, using vMotion to move it from the VMFS5 to a VMFS6 datastore and converting it back to a template solved the issue for me.

**Environment**:
- EKS Anywhere Release: 0.66
- EKS Distro Release:

**Comment by vignesh-goutham** [comment] 2021-09-13 19:43
Hi @f97johan thanks for trying out EKS-A. I was trying to reproduce this issue on my environment and failed to do so. I created a content library on VMFS5, deployed the template from the library to a VMFS5 backed folder and provisoned a vm on VMFS6 datastore from the template on VMFS5 folder. I checked that the full version is VMFS 5.81 on my datastore. Could you please let us know if there is some special configuration that you may have on your environment, that could help us with debugging this issue?

**Comment by bnrjee** [comment] 2021-09-20 18:56
Hi @f97johan, is this still not working for you? If not, would it be possible for you to share the details of any special configurations that you made in your environment?
We could not reproduce this issue locally after following the steps mentioned in the [previous comments](https://github.com/aws/eks-anywhere/issues/158#issuecomment-918518551). It would be very helpful to understand your lab environment better.

**Comment by f97johan** [comment] 2021-09-20 21:27
Hi,

I worked around this by making sure that the template got saved on an VMFS6 datastore and had no issues after that. That was the only thing that I actually changed (based on some semi-related posts online that had issues with templates that had snapshots associated with them on VMFS5 and deploying to VMFS6), but I can't say that I tested it out by again reverting back and storing the template on VMFS5 to see if the problem comes back.

**Comment by bnrjee** [comment] 2021-09-21 19:41
Glad to know that you could get eks-anywhere to work. I am closing this for now. If you find any other problem,  please reopen this ticket or create a new one.

**Closed by bnrjee** 2021-09-21 19:41 UTC
Labels: status/notstarted, status/needinfo
