### ISSUE TITLE
Waiting on namespace which has no pods running

### ISSUE THREAD

**Issue by gohmc** [aws/eks-anywhere#221] opened 2021-09-16 10:48 UTC
Tried to create the local dev cluster as per the [blog](https://aws.amazon.com/blogs/aws/amazon-eks-anywhere-now-generally-available-to-create-and-manage-kubernetes-clusters-on-premises/) demonstrated but the process hung at:

```
2021-09-16T10:16:28.374Z        V4      Task start      {"task_name": "workload-cluster-init"}
2021-09-16T10:16:28.374Z        V0      Creating new workload cluster
2021-09-16T10:16:28.374Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /home/ec2-user:/home/ec2-user -w /home/ec2-user -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 apply -f dev-cluster/generated/dev-cluster-eks-a-cluster.yaml --namespace eksa-system --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig"}
2021-09-16T10:16:29.956Z        V5      Retry execution successful      {"retries": 1, "duration": "1.581950842s"}
2021-09-16T10:16:29.956Z        V3      Waiting for external etcd to be ready
2021-09-16T10:16:29.957Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /home/ec2-user:/home/ec2-user -w /home/ec2-user -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 wait --timeout 60m --for=condition=ManagedEtcdReady clusters.cluster.x-k8s.io/dev-cluster --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig -n eksa-system"}
2021-09-16T10:17:01.603Z        V3      External etcd is ready
2021-09-16T10:17:01.603Z        V3      Waiting for control plane to be ready
2021-09-16T10:17:01.603Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /home/ec2-user:/home/ec2-user -w /home/ec2-user -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 wait --timeout 60m --for=condition=ControlPlaneReady clusters.cluster.x-k8s.io/dev-cluster --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig -n eksa-system"}
```

Noticed the command was waiting on the namespace "eksa-system" which have no pods running:

```
NAMESPACE                           NAME                                                              READY   STATUS    RESTARTS   AGE
capd-system                         capd-controller-manager-659dd5f8bc-6b7pp                          2/2     Running   0          24m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-69889cb844-nmp8l        2/2     Running   0          24m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-6ddc66fb75-ppblp    2/2     Running   0          24m
capi-system                         capi-controller-manager-db59f5789-ps89q                           2/2     Running   0          24m
capi-webhook-system                 capi-controller-manager-64b8c548db-fsxbn                          2/2     Running   0          24m
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-68b8cc9759-lnt8k        2/2     Running   0          24m
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-7dc88f767d-2t5ps    2/2     Running   0          24m
cert-manager                        cert-manager-5f6b885b4-f29hz                                      1/1     Running   0          25m
cert-manager                        cert-manager-cainjector-bb6d9bcb5-zntdt                           1/1     Running   0          25m
cert-manager                        cert-manager-webhook-56cbc8f5b8-8sctg                             1/1     Running   0          25m
etcdadm-bootstrap-provider-system   etcdadm-bootstrap-provider-controller-manager-54476b7bf9-k7tkg    2/2     Running   0          24m
etcdadm-controller-system           etcdadm-controller-controller-manager-d5795556-2bqfc              2/2     Running   0          24m
kube-system                         coredns-7c68f85774-vbkwm                                          1/1     Running   0          25m
kube-system                         coredns-7c68f85774-wcl8h                                          1/1     Running   0          25m
kube-system                         etcd-dev-cluster-eks-a-cluster-control-plane                      1/1     Running   0          25m
kube-system                         kindnet-wtjm9                                                     1/1     Running   0          25m
kube-system                         kube-apiserver-dev-cluster-eks-a-cluster-control-plane            1/1     Running   0          25m
kube-system                         kube-controller-manager-dev-cluster-eks-a-cluster-control-plane   1/1     Running   0          25m
kube-system                         kube-proxy-p6hzl                                                  1/1     Running   0          25m
kube-system                         kube-scheduler-dev-cluster-eks-a-cluster-control-plane            1/1     Running   0          25m
local-path-storage                  local-path-provisioner-666bfc797f-ldgjp                           1/1     Running   0          25m
```

Workload cluster creation failed as a result. Is this a bug or something required to change in the generated spec?

**Comment by TerryHowe** [comment] 2021-09-16 12:24
That pod listing you give appears to be from the kind bootstrap cluster. Are there any other containers running?

**Comment by TerryHowe** [comment] 2021-09-16 12:26
Normally, these type of errors are caused by resource constraints. You may need to increase your RAM and/or disk for Docker or run `docker system prune`

**Comment by gohmc** [comment] 2021-09-17 01:22
How does it related to resources? See the last logged message, the docker run is waiting for non-existent pod in a namespace "eksa-system". On a 2xlarge instance there was at least 50% free memory at the hung point.

**Comment by vignesh-goutham** [comment] 2021-09-17 18:20
That is interesting. I'm assuming you are running a linux distro, so docker technically has access to all the memory(mostly). I have seen this waiting for behavior when the engine runs out of memory. Could you share the output of `docker info --format '{{json .MemTotal}}'`

**Comment by jaxesn** [comment] 2021-09-20 18:46
Its actually not waiting for a pod in the eksa-system namespace, instead its waiting for the `ControlPlaneReady` event which fires from the capi cluster object being created in the eksa-system namespace.

If you this is reproducible for you, maybe looking at the pod logs for the pod in capd-system and the kubelet logs inside the docker container may give us a hint.

**Comment by jaxesn** [comment] 2021-09-20 19:03
Sorry I see your previous issue as well.  Looks like the podcidr is going to be your issue here. I am going to close this one out and well get the podcidr issue fixed.  

Feel free to reopen if you feel closing is an error.

**Closed by jaxesn** 2021-09-20 19:03 UTC
Labels: status/needinfo

**Comment by sagarkundral24** [comment] 2021-09-25 13:24
I found below error in the /var/log/syslog, so I manually pulled that image on the host by doing docker login. That fixed the problem for me.


Error from syslog: 

Unable to find image 'kindest/haproxy:v20210715-a6da3463' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
