### ISSUE TITLE
DiskGiB customization not honored during vSphere Bottlerocket cluster creation

### ISSUE THREAD

**Issue by ptrivedi** [aws/eks-anywhere#4210] opened 2022-11-23 17:57 UTC
**What happened**:

Created vSphere Bottlerocket cluster and specified the DiskGiB size of 500GB via the VSphereMachineConfig object in cluster configuration yaml file. When the cluster VMs got created, they had a disk size of 25GB.

**What you expected to happen**:

Cluster VMs would have 500 GiB disk size.

**How to reproduce it (as minimally and precisely as possible)**:

Specify a custom disk size other than the default of 25 GiB in the cluster config yaml. Create vSphere Bottlerocket cluster.

**Anything else we need to know?**:

EKS Anywhere auto-imports the Bottlerocket template and snapshots it by default. When a template with snapshots is used, CAPV uses the LinkedClone mode to create the vSphere VMs. While LinkedClone mode is much faster than FullClone mode for VM creation and ultimately for speeding up cluster creation process, it does not allow resizing of disks and falls back to the default disk size of 25 GB.

In order to overcome this, a user would have to convert the auto-imported OVA template back to a VM, remove all the snapshots, re-convert it to template. Then use the template to create cluster. The un-snapshotted OVA would allow for custom disk size.

Ideally, EKS Anywhere should detect that the disk size is being customized and avoid auto-snapshotting the imported OVA template in such a case.

**Environment**:
- EKS Anywhere Release:
0.12

- EKS Distro Release:

**Comment by rahulbabu95** [comment] 2023-03-03 01:33
The ticket is a duplicate of #3467 which is fixed in PR #4634
These changes will be available in v0.15 release

**Closed by rahulbabu95** 2023-03-03 01:33 UTC
Labels: kind/bug, priority/p0, area/providers/capv, area/providers/vsphere
