### ISSUE TITLE
[Bare Metal] Auto generated SSH key doesn't work

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#7992] opened 2024-04-15 22:56 UTC
**What happened**: I created a 1 node workload cluster. In my cluster yaml i did not provide an ssh public key. The keys were autogenerated for me and save to disk. Once the node was provisioned and the cluster was up and running successfully, I could not ssh to the node with the eksa generated ssh key. Describing my cluster showed that the key was not the same as the one provided by the CLI.  `kubectl get tinkerbellmachineconfigs.anywhere.eks.amazonaws.com workload-test-cp -o yaml`

**What you expected to happen**:
I should be able to SSH to the node with the eksa generated key.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.19.2
- EKS Distro Release:

**Comment by rajeshvenkata** [comment] 2024-11-19 00:18
Tested the issue with the latest eksctl (v0.21.0) and was unable to reproduce it. I was able to successfully SSH to the node using the eksa auto generated SSH key. Also verified that that the key is same as the one generated by the eksa.

Closing the issue.

**Closed by rajeshvenkata** 2024-11-19 00:18 UTC
