### ISSUE TITLE
vSphere cluster creation: network validation doesn't account for duplicate networks

### ISSUE THREAD

**Issue by etungsten** [aws/eks-anywhere#3162] opened 2022-08-24 23:47 UTC
**What happened**:
Creating a vSphere production cluster hangs on workload cluster creation and times out if `VSphereDatacenterConfig.spec.network` resolves to multiple inventory objects. e.g. 
```
$ govc ls /SDDC-Datacenter/network/sddc-cgw-network-2
/SDDC-Datacenter/network/sddc-cgw-network-2
/SDDC-Datacenter/network/sddc-cgw-network-2

$ govc object.collect /SDDC-Datacenter/network/sddc-cgw-network-2 summary
govc: 2 objects at path "/SDDC-Datacenter/network/sddc-cgw-network-2": [OpaqueNetwork:network-o1008 DistributedVirtualPortgroup:dvportgroup-3588]
```
There is no feedback in the vSphere console that something has gone wrong.

Only describing the `VSphereMachine`s in the bootstrap cluster explains what happened:
```
Status:                                                                                                                            
  Conditions:                                                                                                                      
    Last Transition Time:  2022-08-24T21:43:09Z                                                                                    
    Message:               error getting network specs for "infrastructure.cluster.x-k8s.io/v1beta1, Kind=VSphereVM eksa-system/eks
a-cluster-etcd-7nfsf": unable to find network "/SDDC-Datacenter/network/sddc-cgw-network-2": path '/SDDC-Datacenter/network/sddc-cg
w-network-2' resolves to multiple networks                                                                                         
    Reason:                CloningFailed                                                                                           
    Severity:              Warning                                                                                                 
    Status:                False                                                                                                   
    Type:                  Ready                                                                                                                                                                               
```

With standard vSphere networking, Port Groups cannot have the same name within the same network folder.
But with NSX Data Centers, Port Groups can have the same name, even within the same `DistributedVirtualSwitch`.

**What you expected to happen**:
`eksctl-anywhere` to fail-fast instead of proceeding to workload cluster creation and attempting to create VMs with an ambigious `VSphereDatacenterConfig.spec.network`. 

**How to reproduce it (as minimally and precisely as possible)**:
Have multiple DistributedVirtualPortgroups with the same name and specify `/SDDC-Datacenter/network/<portgroup-name>` in `VSphereDatacenterConfig.spec.network` and try creating an EKS-A vSphere cluster.

Refer to `govc`'s functional test for example: https://github.com/vmware/govmomi/blob/4be89d50c512460b894180592cd898f9783915bd/govc/test/network.bats#L42-L79

**Anything else we need to know?**:
It seems like the fix needs to happen here:
https://github.com/aws/eks-anywhere/blob/3ca04dd71a63edced0e5aae19a1a9eaee456025e/pkg/executables/govc.go#L676-L698
`NetworkExists` needs to ensure there is only one entry returned by `govc find`

Ideally users should be allowed to specify the network segment ID/Logical switch UUID/Managed object ID to uniquely specify the network they'd like to create the VMs with. This would match `govc`'s behavior with `vm.create`, `vm.network.add`. See govc's changes to support this https://github.com/vmware/govmomi/commit/6209be5b5c0bd5d81078fdc82eb4001f202f90e7

For example,
```
$ govc object.collect /SDDC-Datacenter/network/sddc-cgw-network-2 config 
govc: 2 objects at path "/SDDC-Datacenter/network/sddc-cgw-network-2": [OpaqueNetwork:network-o1008 DistributedVirtualPortgroup:dvportgroup-3588]

$ govc object.collect DistributedVirtualPortgroup:dvportgroup-3588 config.logicalSwitchUuid config.segmentId
config.logicalSwitchUuid  string  641a7308-8b8b-4b20-bf4f-c12b235300c6
config.segmentId          string  /infra/tier-1s/cgw/segments/sddc-cgw-network-2
```

I created a separate issue for this: https://github.com/aws/eks-anywhere/issues/3163

**Environment**:
- EKS Anywhere Release: v0.11.1
- EKS Distro Release: N/A
- Bottlerocket Release: Official vmware-k8s-1.22 v1.9.0 OVA

**Comment by vivek-koppuru** [comment] 2022-08-25 04:18
Yea this limitation is by design as we want to resolve to the right network, but the solution seems to be in #3163

**Comment by g-gaston** [comment] 2022-08-30 16:44
Closing since it seems we answered/resolved the issue, please re-open as needed or just let me know if there is still something pending

**Closed by g-gaston** 2022-08-30 16:44 UTC
Labels: external, ack
