### ISSUE TITLE
EKS-A 1.23 eksa-auth-refresher pod CrashLoopBackOff

### ISSUE THREAD

**Issue by RobertNorthard** [aws/eks-anywhere#3143] opened 2022-08-24 09:59 UTC
**What happened**:

After installing EKS-A 1.23 on vSphere without configuring EKS-A Curated Packages the eksa-auth-refresher pod has a CrashLoopBackOff due to the following error:

`MissingRegion: could not find region configuration`

**What you expected to happen**:

EKS-A curated packages deployments to not be installed if curated packages not configured.

**How to reproduce it (as minimally and precisely as possible)**:

Install new EKS-A cluster on vSphere without curated packages configured.

**Anything else we need to know?**:

N/A

**Environment**:
- EKS Anywhere Release: v0.11.1
- EKS Distro Release: 1.23

**Comment by lewisdiamond** [comment] 2022-08-25 18:35
Duplicate of #3039
We'll at least make it so the job doesn't get into CrashLoopBackOff state, however, this job will no longer be needed in a couple of months.

**Closed** 2022-08-25 18:35 UTC
Labels: external, team/packages

**Comment by TerryHowe** [comment] 2022-08-25 18:49
https://github.com/aws/eks-anywhere-packages/pull/440
