### ISSUE TITLE
Investigate the possibility of vSphere VMs being created 'reserved' memory instead of 'overcommitted' memory during vSphere cluster creation

### ISSUE THREAD

**Issue by ptrivedi** [aws/eks-anywhere#4211] opened 2022-11-23 18:07 UTC
**What would you like to be added**:

Requires research and investigation on vSphere side and/or EKS Anywhere side.

Investigate if there is a setting on vSphere or if CAPV can trigger VM creation indicating specifically to only 'reserve' memory and not 'overcommit' it.

**Why is this needed**:

According to a customer report, vSphere cluster VMs created by EKS Anywhere show as much swap space as the requested memory, resulting in double memory requirements. This is not an EKS Anywhere issue, it needs to be investigated if vSphere allows specifying that memory should only be reserved during VM creation, and the change would be either on CAPV side or a generic setting on vSphere environment.

**Comment by drewvanstone** [comment] 2022-12-06 22:46
Duplicate of https://github.com/aws/eks-anywhere/issues/4237

**Closed as completed by drewvanstone** 2022-12-06 22:46 UTC
Labels: kind/enhancement, priority/p0, area/providers/capv, area/providers/vsphere
