### ISSUE TITLE
Multiple worker node groups additional features

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#1046] opened 2022-01-26 15:04 UTC
**What would you like to be added**:

- [ ] Add support for setting kubernetes version at worker node level
- [ ] Add support for upgrading worker node groups independently

**Why is this needed**:

Some users will want to setup a blue/green deployment like setup using worker node groups where they can better control the roll out of upgrades.  We could support these use cases if we allow worker node groups to be versioned independently of the control plane (assuming within the standard n-2 support policy).

**Comment by chrisdoherty4** [comment] 2023-07-28 18:40
Duplicate of https://github.com/aws/eks-anywhere-internal/issues/1376.

**Closed by chrisdoherty4** 2023-07-28 18:40 UTC
Labels: kind/enhancement, team/cli, area/cli
