### ISSUE TITLE
EKS Anywhere's write-netplan workflow action failed because it is not able to get host network interface

### ISSUE THREAD

**Issue by ph-armada** [aws/eks-anywhere#6261] opened 2023-07-25 16:53 UTC
**What happened**:
EKS Anywhere's write-netplan workflow action failed because it is not able to get host network interface.

**What you expected to happen**:
EKS Anywhere's write-netplan workflow action should be able to retrieve host network interface info and then write the netplan config accordingly and correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Follow EKS Anywhere bare metal cluster creation instruction with an Ubuntu image.

**Anything else we need to know?**:
The issue is from this line of code:
https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/tinkerbell/hub/patches/0003-Write-DHCP-offer-to-static-Netplan-file.patch#L219
```
+	// Change to PID 1 network namespace for working with the host's interfaces.
+	ns1, err := netns.GetFromPid(1)
```

**Environment**:
- EKS Anywhere Release: v0.16.2
- EKS Distro Release: `public.ecr.aws/eks-anywhere/tinkerbell/hub/writefile:6c0f0d437bde2c836d90b000312c8b25fa1b65e1-eks-a-15`

**Comment by jacobweinstock** [comment] 2023-07-28 16:27
Hey @ph-armada, thanks for the report. Just for reference sake this is the same issue filed here: https://github.com/aws/eks-anywhere-build-tooling/issues/2217

**Comment by chrisdoherty4** [comment] 2023-09-07 14:30
Closed as duplicate of https://github.com/aws/eks-anywhere-build-tooling/issues/2217

**Closed by chrisdoherty4** 2023-09-07 14:30 UTC
Labels: area/providers/tinkerbell, external
