### ISSUE TITLE
Kubernetes network policy gets ignored

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#4406] opened 2022-12-14 13:58 UTC
**What happened**:
I am applying network policy to allow collecting flux metrics through nodeports but seems EKS-A cilium ignores it. Here is my network policy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping-through-nodeport
  namespace: flux-system
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: 172.27.48.0/24
      ports:
        - port: 8080
```

Even if I apply it, I get the following drop message through `cilium monitor --type drop`:
_xx drop (Policy denied) flow 0xac2e1c00 to endpoint 3065, , identity world->53020: 172.27.48.111:25644 -> 100.80.1.171:8080 tcp SYN_

BUT if I change the **`cidr` to `0.0.0.0/0` then the connection works as it should**.

Why does 0.0.0.0/0 works while the proper cidr does not?

**What you expected to happen**:
Proper/stricter cidr works as well.

**How to reproduce it (as minimally and precisely as possible)**:
* Install EKS-A with default CNI settings
* Create a nodeport service:
```
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app: helm-controller
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32766
      name: prom-nodeport
```
* Apply a network policy to allow it using your remote host cidr (see above the example network policy)
* Try to hit the nodeport with curl

**Anything else we need to know?**:
I guess it could be helpful: I used the following commands to start the monitor in the proper cilium pod:
```
export PODNAME=helm-controller-5b795444b4-b74c2
export PODNAMESPACE=flux-system
kubectl -n kube-system exec -ti $(kubectl get pods -n kube-system -o wide |grep cilium|grep $(kubectl get pod $PODNAME -n $PODNAMESPACE -o jsonpath='{.spec.nodeName}')|grep -v operator|awk '{print $1}') -- cilium monitor --type drop
```

**Environment**:
- EKS Anywhere Release: v0.12.2
- EKS Distro Release: 1.24

**Comment by g-gaston** [comment] 2022-12-19 16:41
Thanks for the report @Cajga! We will try to reproduce it on our end.

**Comment by g-gaston** [comment] 2022-12-19 16:48
Hey @Cajga could you provide your cluster config yaml?
Specially the cilium config part

**Comment by Cajga** [comment] 2022-12-21 10:35
Hi @g-gaston,

Sure, here is the `kind: Cluster` of our config:
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eks-a-bm-poc
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 100.80.0.0/16
    services:
      cidrBlocks:
      - 100.81.0.0/16
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "192.168.35.68"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eks-a-bm-poc-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eks-a-bm-poc
  kubernetesVersion: "1.24"
  managementCluster:
    name: eks-a-bm-poc
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eks-a-bm-worker01
    name: worker01
  identityProviderRefs:
  - kind: OIDCConfig
    name: eks-anywhere-azuread
  gitOpsRef:
    name: kubernetes-infra-addons
    kind: FluxConfig
```

**Comment by chrisdoherty4** [comment] 2023-01-25 16:45
Hi @Cajga. Apologies for the long wait, we can reproduce the issue but haven't determined the root cause.

To clarify your setup, you're trying to apply a network policy that limits traffic to that originating outside the cluster?

**Comment by Cajga** [comment] 2023-01-25 16:58
Hi @chrisdoherty4,

Correct. In this particular example, we have a prometheus cluster outside of the EKS-A cluster. We would like to make sure that only the prometheus cluster nodes can scrape the flux controller metrics which is exposed through node-ports.

**Comment by chrisdoherty4** [comment] 2023-10-24 19:23
@Cajga I have some new information.

```
It's a limitation of all nodePort (and loadBalancer) type services (and their implementations). The way they work is by hiding (SNAT'ing) the original source IP behind the node IP. It's documented here: [kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport)
With this in mind, it is impossible to implement any filtering based on the source IP next to the Pod because that information is already lost.

The solution to that is to use externalTrafficPolicy=Local: [kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip). This way the source IP is preserved, so that a Pod sees the original client IP, so does Cilium eBPF program attached to the Pod's interface. So in this case, Cilium would be able to block the traffic based on the cidr: w.x.y.z/nn field
```

`externalTrafficPolicy=Local` comes with its own challenges. I'm closing the ticket as I don't believe there's any work to be done, but we can continue the discussion.

**Closed by chrisdoherty4** 2023-10-24 19:23 UTC
Labels: external, team/providers, area/cni, triage/accepted

**Comment by Cajga** [comment] 2023-10-26 11:22
Hi @chrisdoherty4 ,

Thanks for looking into this. In fact, I also run into this at a later stage and opened a Cilium ticket about it. The outcome was the same that you said: we need to preserve the source IP for this.
`externalTrafficPolicy=Local` requires extra work on the client/DNS side so, we would like to avoid it. As you most probably aware of, Cilium has the possibility to replace kube-proxy and with this setup there are ways with Cilium to achieve [client source IP preservation](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#client-source-ip-preservation) without the need to use `externalTrafficPolicy=Local`.

I've opened [this ticket](https://github.com/aws/eks-anywhere/issues/6409) to request the possibility to install EKS-A without kube-proxy. This would allow users to use different Cilium modes to preserve source IP and fix this issue as well. On top of this, it would also enable them to use other, advanced Cilium features like the [Gateway API implementation](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#gs-gateway-api) that also requires the kube-proxy-less mode.
